; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 578
global g_ImportsGameVersionPostFix64 := ".1"
=======
global g_ImportsGameVersion64 := 547
global g_ImportsGameVersionPostFix64 := ""
>>>>>>> Stashed changes
