; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 618
global g_ImportsGameVersionPostFix64 := ".2"
=======
global g_ImportsGameVersion64 := 601
global g_ImportsGameVersionPostFix64 := ""
>>>>>>> Stashed changes
