; Automatically generated by Addon Management
#include *i %A_LineFile%\..\IC_Core\IC_Core_Includes.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_Performance\IC_BrivGemFarm_Component.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_AdvancedSettings\IC_BrivGemFarm_AdvancedSettings_Includes.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_Stats\IC_BrivGemFarm_Stats_Component.ahk
#include *i %A_LineFile%\..\IC_About\IC_About_Component.ahk
#include *i %A_LineFile%\..\IC_InventoryView\IC_InventoryView_Component.ahk
#include *i %A_LineFile%\..\IC_Theme_Manager\IC_Theme_Manager_Includes.ahk
